name: Generate Minecraft Map

on:
  push:
    paths:
      - 'data/**.json'
      - 'map_plot.py'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        playwright install --with-deps

    - name: Generate map
      run: |
        python map_plot.py

    - name: Generate preview image
      run: |
        python generate_preview.py

     - name: Commit & Push generated map + preview
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
        git add index.html preview.png
        git commit -m "🔄 auto: regenerate map and preview" || echo "No changes to commit"
        git push
