name: Generate Minecraft Map

on:
  push:
    paths:
      - 'data/**.json'
      - 'map_plot.py'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Generate map
      run: |
        python map_plot.py

        - name: Commit & Push generated map
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
        git add index.html
        git commit -m "🔄 auto: regenerate map on update" || echo "No changes to commit"
        git push

